"Para regenerar su contrase&ntilde;a, pulse sobre el link que encontrar&aacute; a continuaci&oacute;n:"
"<br /><br />"
"<a href='http://www.mesafija.com/admin/regpswd.php?clave="+@user.clave+"'>Regenerar</a>"
"<br /><br />"
"El equipo de Mesafija.com"